#生产环境
server:
  servlet:
    path: /api/v1
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://123.207.93.53:3306/love-api?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://localhost:3306/love-api?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gy123456
    #password: mysql123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gy.love.loveapi.entity
  configuration:
    mapUnderscoreToCamelCase: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志
logging:
  level:
    com.gy.love.loveapi.mapper: DEBUG